---
title: "Completeness"
author: "Eric Voorhis"
date: "November 30, 2016"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r }
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(datasets)
library(ggrepel)

completeness <- function(dataframe) {
  df <- bind_rows(
    lapply(dataframe, function(x) {
      data.frame(nmiss=sum(is.na(x)),
                 n=length(x),
                 completeness= 1 - (sum(is.na(x))/length(x)))
    })
  )
  cbind(colname=colnames(dataframe), df)
}

na_list <- c("", " ", "Not Available", "NA", "NAN", "Not Applicable")

process_csv <- function(file_name) {
  df <- read.csv(file_name, na.strings=na_list)
  df$State <- as.character(df$State)
  fifty <- which(df$State %in% state.abb)
  datareturn <- df[fifty,]
  return(datareturn)
}

mortality_types <- c("Acute Myocardial Infarction (AMI) 30-Day Mortality Rate",
                     "Heart failure (HF) 30-Day Mortality Rate")

setwd("C:\\Users\\EricV\\work\\projects\\group_project_2\\data")

df_surveys <- process_csv("HCAHPS - Hospital.csv")
df_death <- process_csv("Readmissions and Deaths - Hospital.csv")
df_ratings <- process_csv("Hospital General Information.csv")
df_payments <- process_csv("Payment and Value of Care - Hospital.csv")
df_timely <- process_csv("Timely and Effective Care - Hospital.csv")

plotCompleteness <- function(data_frame, title) {
  completion_df <- completeness(data_frame)
  ggplot(completion_df, aes(x=reorder(factor(colname), completeness), y=completeness)) + 
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
}

df_death_subset_ami <- df_death %>%
  filter(Measure.Name == "Acute Myocardial Infarction (AMI) 30-Day Mortality Rate")

df_death_subset_hf <- df_death %>%
  filter(Measure.Name == "Heart failure (HF) 30-Day Mortality Rate")

death_completeness <- completeness(df_death)
death_completeness_ami <- completeness(df_death_subset_ami)
death_completeness_hf <- completeness(df_death_subset_hf)

completeness_ami_by_state <- df_death_subset_ami %>%
  group_by(State) %>%
  summarise(nmiss=sum(is.na(Score)),
            n=length(Score),
            completeness=1-(sum(is.na(Score))/length(Score)))

completeness_by_state_all <- df_death %>%
  group_by(State) %>%
  summarise(nmiss=sum(is.na(Score)),
            n=length(Score),
            completeness=1-(sum(is.na(Score))/length(Score)))
  
completeness_ami_by_state$subset_type <- "Myocardial Infarction"
completeness_by_state_all$subset_type <- "All"
```

## Completeness

Missing values show up in several forms:
* ""
* " "
* Not Available
* NA
* NAN
* Not Applicable

## Completeness of flat files

```{r }
plotCompleteness(df_surveys)
plotCompleteness(df_death)
```

## Completeness by state

```{r }
ggplot(rbind(completeness_ami_by_state, completeness_by_state_all),
       aes(x=reorder(State, completeness), y=completeness, color=subset_type)) +
  geom_point(size=2)
```
